# Generated by Django 5.2 on 2025-04-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('payments', '0001_initial'),
        ('pet_app', '0004_pets_appointment_status_alter_pets_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'Payments', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-id'], 'verbose_name': 'Transactions', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='payment',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet_app.pets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
