# Generated by Django 5.2 on 2025-04-08 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('DOG', 'DOG'), ('CAT', 'CAT'), ('BIRD', 'BIRD'), ('REPTILE', 'REPTILE'), ('FISH', 'FISH'), ('OTHER', 'OTHER')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=25, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNKNOWN', 'UNKNOWN')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('status', models.CharField(choices=[('OWNED', 'OWNED'), ('FOSTER', 'FOSTER')], max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('adm_number', models.CharField(max_length=50)),
                ('last_vet_visit', models.DateField(blank=True, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('service_type', models.CharField(choices=[('GROOMING', 'GROOMING'), ('PET SPA', 'PET SPA'), ('TRAINING', 'TRAINING'), ('PET SITTING', 'PET SITTING'), ('VETERINARY', 'VETERINARY'), ('VACCINATION', 'VACCINATION'), ('PET PHOTOGRAPHY', 'PET PHOTOGRAPHY')], max_length=20)),
                ('appointment_date', models.DateField()),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['id'],
            },
        ),
    ]
