# Generated by Django 5.2 on 2025-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_pets_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SCHEDULED', 'SCHEDULED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='Scheduled', max_length=50),
        ),
    ]
