# Generated by Django 5.2 on 2025-04-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0003_alter_pets_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='appointment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SCHEDULED', 'SCHEDULED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='Scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='pets',
            name='status',
            field=models.CharField(choices=[('OWNED', 'OWNED'), ('FOSTER', 'FOSTER')], max_length=20),
        ),
    ]
