# Generated by Django 5.2 on 2025-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0004_pets_appointment_status_alter_pets_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='adm_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
