# Generated by Django 5.2 on 2025-04-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0005_alter_pets_adm_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='appointment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SCHEDULED', 'SCHEDULED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='SCHEDULED', max_length=50),
        ),
    ]
