# Generated by Django 5.2 on 2025-04-14 13:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('id_card', models.ImageField(blank=True, null=True, upload_to='veterinary/')),
                ('place', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Veterinarian',
                'verbose_name_plural': 'Veterinarian',
                'ordering': ['id'],
            },
        ),
    ]
